### ISSUE TITLE
Error occur after compile

### ISSUE THREAD

**Issue by xiaomingdaily** [PortSwigger/replicator#3]
environment: windows 7.

java.lang.NoClassDefFoundError: org/json/JSONException
	at burp.ReplicatorPanel.<init>(ReplicatorPanel.java:57)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at burp.vuc.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.json.JSONException
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more

**Comment by pajswigger** [comment]
Hi xiaomingdaily, how are you compiling? I recommend you use Gradle, then use replicator-all.jar
